app:
  s3:
    bucket: makeuplion
cloud:
  aws:
    credentials:
      access-key: AKIAZI2LB4TZRX5GP27P
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false